### ISSUE TITLE
Note should Left align with Copy Below 

### ISSUE THREAD

**Issue by danielsunden** [UrbanInstitute/inclusion#19]
<img width="552" alt="screen shot 2018-04-20 at 11 21 44 am" src="https://user-images.githubusercontent.com/4601111/39064830-183e63da-448d-11e8-8689-0ba0fbfec4ae.png">

**Comment by bchartoff** [comment]
Closed by 5a85ae4dd7ce9c36f260f6e0b607b9a412463541
